import './components/header-component.js'
import './components/products-component.js'
import './components/detail-component.js'
import './components/summary-component.js'
import './components/navbar-component.js'
import './components/buttons-component.js'